["Crack Hammer Durability"]
	copper = 64
	gold = 96
	iron = 128
	steel = 160
	diamond = 256
	netherite = 384
["Chisel Durability"]
	copper = 10
	gold = 15
	iron = 30
	steel = 45
	diamond = 64
	netherite = 96
["Scythe Harvest Radius"]
	# Range: 1 ~ 3 - Default: 1
	radius = 1
["Block and Mob Loot Settings"]
	# Determine the chance with which an item can drop from Ores and Mobs.
	# 0.0 = 0% ~ 1.0 = 100%
	diamond_nugget_from_diamond_ore = 0.15
	diamond_nugget_from_coal_ore = 0.025
	emerald_nugget_from_ore = 0.075
	copper_nugget_from_ore = 0.1
	garlic_from_zombie = 0.2
	sulfur_from_creeper = 0.2
	saltpeter_from_creeper = 0.2
	saltpeter_from_bricks = 0.5
["Structure Loot Settings"]
	# Determine the chance with which an item could be generated in any structures.
	# 0.0 = 0% ~ 1.0 = 100%
	sulfur_dust = 0.25
	saltpeter_dust = 0.25
	copper_dust = 0.25
	iron_dust = 0.2
	gold_dust = 0.2
	carbon_dust = 0.4
	diamond_dust = 0.1
	emerald_dust = 0.1
	steel_dust = 0.2
	netherite_scrap_dust = 0.05
	netherite_dust = 0.05
	diamond_nugget = 0.1
	emerald_nugget = 0.15
	copper_nugget = 0.2
	steel_ingot = 0.1
	garlic = 0.4
	copper_crack_hammer = 0.15
	iron_crack_hammer = 0.1
	steel_crack_hammer = 0.08
